services:
  postgresql:
    container_name: ms_pg_sql
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: amal
      POSTGRES_PASSWORD: amal1234
      POSTGRES_DB: docvectors
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped


volumes:
  postgres:

networks:
  microservices-net:
